;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                  clock.INC                                 ;
;                            Clock - MP3 includefile                         ;
;                                   EE/CS 52                                 ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Description:   This function contains the definitions related to the MP3
;                internal clock.

;Revision History:
;    5/7/16    Tim Liu   there are no clock definitions, so file left blank



